using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Progress.Sitefinity.AspNetCore.Widgets.Models.Facets
{
    internal static class WidgetSettingsFacetFieldMapper
    {
        internal static string GetIntervalDateTime(string dateStep)
        {
            if (!string.IsNullOrEmpty(dateStep))
            {
                switch (dateStep)
                {
                    case "0":
                        return "day";
                    case "1":
                        return "week";
                    case "2":
                        return "month";
                    case "3":
                        return "quarter";
                    case "4":
                        return "year";
                }
            }

            // UX: if there is no step specified we fallback to a day interval.
            return "day";
        }

        internal static List<Facet> MapWidgetSettingsToFieldsModel(IEnumerable<FacetField> selectedFacetsToBeUsed)
        {
            var facetFields = new List<Facet>();
            foreach (var facet in selectedFacetsToBeUsed)
            {
                var facetFieldName = facet.FacetableFieldNames.FirstOrDefault();

                var settings = facet.FacetFieldSettings;

                if (facet.FacetFieldSettings.RangeType == SearchFacetExtensions.AutoGeneratedFacet)
                {
                    if (settings.IsValueFacet())
                    {
                        facetFields.Add(CreateValueFacetFieldModel(facetFieldName, settings));
                    }
                    else if (settings.FacetType == SearchIndexAdditonalFieldType.NumberWhole.ToString() ||
                             settings.FacetType == SearchIndexAdditonalFieldType.NumberDecimal.ToString())
                    {
                        facetFields.Add(CreateNumberIntervalFacetFieldModel(facetFieldName, settings));
                    }
                    else if (settings.FacetType == SearchIndexAdditonalFieldType.DateAndTime.ToString())
                    {
                        facetFields.Add(CreateDateIntervalFacetFieldModel(facetFieldName, settings));
                    }
                }
                else
                {
                    if (settings.FacetType == SearchIndexAdditonalFieldType.NumberWhole.ToString() ||
                        settings.FacetType == SearchIndexAdditonalFieldType.NumberDecimal.ToString())
                    {
                        facetFields.Add(CreateNumberRangeFacetFieldModel(facetFieldName, settings));
                    }
                    else if (settings.FacetType == SearchIndexAdditonalFieldType.DateAndTime.ToString())
                    {
                        facetFields.Add(CreateDateRangeFacetFieldModel(facetFieldName, settings));
                    }
                }
            }

            return facetFields;
        }

        private static Facet CreateDateRangeFacetFieldModel(string facetFieldName, Settings settings)
        {
            var rangeList = new List<CustomFacetRange>();
            foreach (var range in settings.DateRanges)
            {
                var valueFrom = range.From.HasValue ? range.From.Value.ToUniversalTime().ToString(DateTimeFormat, CultureInfo.InvariantCulture) : null;
                var valueTo = range.To.HasValue ? range.To.Value.ToUniversalTime().ToString(DateTimeFormat, CultureInfo.InvariantCulture) : null;

                if (valueFrom != null && valueTo != null)
                {
                    rangeList.Add(new CustomFacetRange() { From = valueFrom, To = valueTo });
                }
            }

            return new Facet()
            {
                FieldName = facetFieldName,
                CustomIntervals = new List<CustomFacetRange>(rangeList),
                FacetFieldType = settings.FacetType,
                SitefinityFacetType = SitefinityFacetType.Range,
            };
        }

        private static Facet CreateNumberRangeFacetFieldModel(string facetFieldName, Settings settings)
        {
            var rangeList = new List<CustomFacetRange>();
            if (settings.NumberRanges != null)
            {
                rangeList.AddRange(
                    settings
                    .NumberRanges
                    .Select(range => new CustomFacetRange() { From = range.From.ToString(), To = range.To.ToString() }));
            }

            if (settings.NumberRangesDecimal != null)
            {
                rangeList.AddRange(
                    settings
                    .NumberRangesDecimal
                    .Select(range => new CustomFacetRange() { From = range.From.ToString(), To = range.To.ToString() }));
            }

            return new Facet()
            {
                FieldName = facetFieldName,
                CustomIntervals = new List<CustomFacetRange>(rangeList),
                FacetFieldType = settings.FacetType,
                SitefinityFacetType = SitefinityFacetType.Range,
            };
        }

        private static Facet CreateDateIntervalFacetFieldModel(string facetFieldName, Settings settings)
        {
            return new Facet()
            {
                FieldName = facetFieldName,
                IntervalRange = GetIntervalDateTime(settings.DateStep),
                FacetFieldType = settings.FacetType,
                SitefinityFacetType = SitefinityFacetType.Interval,
            };
        }

        private static Facet CreateNumberIntervalFacetFieldModel(string facetFieldName, Settings settings)
        {
            return new Facet()
            {
                FieldName = facetFieldName,
                IntervalRange = settings.NumberStep.ToString(),
                FacetFieldType = settings.FacetType,
                SitefinityFacetType = SitefinityFacetType.Interval,
            };
        }

        private static Facet CreateValueFacetFieldModel(string facetFieldName, Settings settings)
        {
            return new Facet()
            {
                FieldName = facetFieldName,
                SitefinityFacetType = SitefinityFacetType.Value,
                FacetFieldType = settings.FacetType,
            };
        }

        internal const string DateTimeFormat = "yyyy-MM-ddTHH:mm:ss.fffZ";
    }
}
